name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the action on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Setup Node.js (required for some actions)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build the site
      run: |
        # If you need to do some build step, include commands here
        # For static HTML, this may not be necessary.

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./files  # Folder containing your HTML/CSS files
